package hatfieldjuniorswimmingschool.view;


import hatfieldjuniorswimmingschool.controller.BookingController;
import hatfieldjuniorswimmingschool.controller.LessonController;
import hatfieldjuniorswimmingschool.controller.RatingController;
import hatfieldjuniorswimmingschool.controller.UserController;
import hatfieldjuniorswimmingschool.model.User;
import java.awt.Image;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


public class MonthlyReport extends javax.swing.JFrame {
    private int userId;
    private String user_name;
    
    /**
     * Creates new form MonthlyReport
     */
    //create constructor with parameter
    public MonthlyReport(int userId) {
        initComponents();
        this.userId = userId;
        getMonthlyLearnerReport();
        getMonthlyCoachReport();
        fetchLessonRating();
        //set background image
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/hatfieldjuniorswimmingschool/image/swim6.jpg")).getImage().getScaledInstance(1530, 829, Image.SCALE_DEFAULT));
        backgroundImage.setIcon(imageIcon);
    }

     public MonthlyReport() {
        initComponents();
        getMonthlyLearnerReport();
        getMonthlyCoachReport();
        fetchLessonRating();
        //set background image
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/hatfieldjuniorswimmingschool/image/swim6.jpg")).getImage().getScaledInstance(1530, 829, Image.SCALE_DEFAULT));
        backgroundImage.setIcon(imageIcon);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backHomeButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        selectName = new javax.swing.JLabel();
        selectStatus = new javax.swing.JLabel();
        selectPrice = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ratingReport = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        selectName2 = new javax.swing.JLabel();
        selectStatus2 = new javax.swing.JLabel();
        selectPrice2 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        coachReport1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        selectName4 = new javax.swing.JLabel();
        selectStatus4 = new javax.swing.JLabel();
        selectPrice4 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        coachReport2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        selectName5 = new javax.swing.JLabel();
        selectStatus5 = new javax.swing.JLabel();
        selectPrice5 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        coachReport3 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        selectName6 = new javax.swing.JLabel();
        selectStatus6 = new javax.swing.JLabel();
        selectPrice6 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        coachReport4 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        selectName7 = new javax.swing.JLabel();
        selectStatus7 = new javax.swing.JLabel();
        selectPrice7 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        coachReport5 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        selectName8 = new javax.swing.JLabel();
        selectStatus8 = new javax.swing.JLabel();
        selectPrice8 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        coachReport6 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        selectName9 = new javax.swing.JLabel();
        selectStatus9 = new javax.swing.JLabel();
        selectPrice9 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        coachReport7 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        selectName1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userReport = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        selectName10 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        coachReport = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        selectName11 = new javax.swing.JLabel();
        selectStatus11 = new javax.swing.JLabel();
        selectPrice11 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        coachReport9 = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        selectName12 = new javax.swing.JLabel();
        selectStatus12 = new javax.swing.JLabel();
        selectPrice12 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        coachReport10 = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        selectName13 = new javax.swing.JLabel();
        selectStatus13 = new javax.swing.JLabel();
        selectPrice13 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        coachReport11 = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        selectName14 = new javax.swing.JLabel();
        selectStatus14 = new javax.swing.JLabel();
        selectPrice14 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        coachReport12 = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        selectName15 = new javax.swing.JLabel();
        selectStatus15 = new javax.swing.JLabel();
        selectPrice15 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        coachReport13 = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        selectName16 = new javax.swing.JLabel();
        selectStatus16 = new javax.swing.JLabel();
        selectPrice16 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        coachReport14 = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        selectName17 = new javax.swing.JLabel();
        selectStatus17 = new javax.swing.JLabel();
        selectPrice17 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        coachReport15 = new javax.swing.JTable();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1530, 829));
        setPreferredSize(new java.awt.Dimension(1530, 829));
        getContentPane().setLayout(null);

        backHomeButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backHomeButton.setForeground(new java.awt.Color(0, 102, 255));
        backHomeButton.setText("Back To HomePage");
        backHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backHomeButton);
        backHomeButton.setBounds(90, 110, 300, 40);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        selectName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName.setForeground(new java.awt.Color(0, 102, 255));
        jPanel4.add(selectName);
        selectName.setBounds(153, 78, 147, 20);

        selectStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus.setForeground(new java.awt.Color(0, 102, 255));
        jPanel4.add(selectStatus);
        selectStatus.setBounds(153, 228, 147, 25);

        selectPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice.setForeground(new java.awt.Color(0, 102, 255));
        jPanel4.add(selectPrice);
        selectPrice.setBounds(153, 259, 147, 25);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 0, 255));
        jLabel36.setText("Lesson Rating Details");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(110, 40, 220, 22);

        ratingReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ratingReport.setForeground(new java.awt.Color(0, 51, 255));
        ratingReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Lesson Name", "Rating"
            }
        ));
        ratingReport.setRowHeight(30);
        jScrollPane1.setViewportView(ratingReport);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 390, 440);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        selectName2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName2.setForeground(new java.awt.Color(0, 102, 255));
        jPanel6.add(selectName2);
        selectName2.setBounds(153, 78, 147, 20);

        selectStatus2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus2.setForeground(new java.awt.Color(0, 102, 255));
        jPanel6.add(selectStatus2);
        selectStatus2.setBounds(153, 228, 147, 25);

        selectPrice2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice2.setForeground(new java.awt.Color(0, 102, 255));
        jPanel6.add(selectPrice2);
        selectPrice2.setBounds(153, 259, 147, 25);

        jLabel38.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 0, 255));
        jLabel38.setText("Monthly Coach Report");
        jPanel6.add(jLabel38);
        jLabel38.setBounds(120, 20, 220, 22);

        coachReport1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport1.setForeground(new java.awt.Color(0, 51, 255));
        coachReport1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport1.setRowHeight(30);
        jScrollPane3.setViewportView(coachReport1);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(30, 90, 340, 190);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(550, 290, 440, 310);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        selectName4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName4.setForeground(new java.awt.Color(0, 102, 255));
        jPanel8.add(selectName4);
        selectName4.setBounds(153, 78, 147, 20);

        selectStatus4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus4.setForeground(new java.awt.Color(0, 102, 255));
        jPanel8.add(selectStatus4);
        selectStatus4.setBounds(153, 228, 147, 25);

        selectPrice4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice4.setForeground(new java.awt.Color(0, 102, 255));
        jPanel8.add(selectPrice4);
        selectPrice4.setBounds(153, 259, 147, 25);

        jLabel40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 0, 255));
        jLabel40.setText("Monthly Coach Report");
        jPanel8.add(jLabel40);
        jLabel40.setBounds(120, 20, 220, 22);

        coachReport2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport2.setForeground(new java.awt.Color(0, 51, 255));
        coachReport2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport2.setRowHeight(30);
        jScrollPane5.setViewportView(coachReport2);

        jPanel8.add(jScrollPane5);
        jScrollPane5.setBounds(30, 90, 340, 190);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        selectName5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName5.setForeground(new java.awt.Color(0, 102, 255));
        jPanel9.add(selectName5);
        selectName5.setBounds(153, 78, 147, 20);

        selectStatus5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus5.setForeground(new java.awt.Color(0, 102, 255));
        jPanel9.add(selectStatus5);
        selectStatus5.setBounds(153, 228, 147, 25);

        selectPrice5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice5.setForeground(new java.awt.Color(0, 102, 255));
        jPanel9.add(selectPrice5);
        selectPrice5.setBounds(153, 259, 147, 25);

        jLabel41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 0, 255));
        jLabel41.setText("Monthly Coach Report");
        jPanel9.add(jLabel41);
        jLabel41.setBounds(120, 20, 220, 22);

        coachReport3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport3.setForeground(new java.awt.Color(0, 51, 255));
        coachReport3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport3.setRowHeight(30);
        jScrollPane6.setViewportView(coachReport3);

        jPanel9.add(jScrollPane6);
        jScrollPane6.setBounds(30, 90, 340, 190);

        jPanel8.add(jPanel9);
        jPanel9.setBounds(550, 290, 440, 310);

        jPanel4.add(jPanel8);
        jPanel8.setBounds(550, 290, 440, 310);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(null);

        selectName6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName6.setForeground(new java.awt.Color(0, 102, 255));
        jPanel10.add(selectName6);
        selectName6.setBounds(153, 78, 147, 20);

        selectStatus6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus6.setForeground(new java.awt.Color(0, 102, 255));
        jPanel10.add(selectStatus6);
        selectStatus6.setBounds(153, 228, 147, 25);

        selectPrice6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice6.setForeground(new java.awt.Color(0, 102, 255));
        jPanel10.add(selectPrice6);
        selectPrice6.setBounds(153, 259, 147, 25);

        jLabel42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 0, 255));
        jLabel42.setText("Monthly Coach Report");
        jPanel10.add(jLabel42);
        jLabel42.setBounds(120, 20, 220, 22);

        coachReport4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport4.setForeground(new java.awt.Color(0, 51, 255));
        coachReport4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport4.setRowHeight(30);
        jScrollPane7.setViewportView(coachReport4);

        jPanel10.add(jScrollPane7);
        jScrollPane7.setBounds(30, 90, 340, 190);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(null);

        selectName7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName7.setForeground(new java.awt.Color(0, 102, 255));
        jPanel11.add(selectName7);
        selectName7.setBounds(153, 78, 147, 20);

        selectStatus7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus7.setForeground(new java.awt.Color(0, 102, 255));
        jPanel11.add(selectStatus7);
        selectStatus7.setBounds(153, 228, 147, 25);

        selectPrice7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice7.setForeground(new java.awt.Color(0, 102, 255));
        jPanel11.add(selectPrice7);
        selectPrice7.setBounds(153, 259, 147, 25);

        jLabel43.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 0, 255));
        jLabel43.setText("Monthly Coach Report");
        jPanel11.add(jLabel43);
        jLabel43.setBounds(120, 20, 220, 22);

        coachReport5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport5.setForeground(new java.awt.Color(0, 51, 255));
        coachReport5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport5.setRowHeight(30);
        jScrollPane8.setViewportView(coachReport5);

        jPanel11.add(jScrollPane8);
        jScrollPane8.setBounds(30, 90, 340, 190);

        jPanel10.add(jPanel11);
        jPanel11.setBounds(550, 290, 440, 310);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(null);

        selectName8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName8.setForeground(new java.awt.Color(0, 102, 255));
        jPanel12.add(selectName8);
        selectName8.setBounds(153, 78, 147, 20);

        selectStatus8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus8.setForeground(new java.awt.Color(0, 102, 255));
        jPanel12.add(selectStatus8);
        selectStatus8.setBounds(153, 228, 147, 25);

        selectPrice8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice8.setForeground(new java.awt.Color(0, 102, 255));
        jPanel12.add(selectPrice8);
        selectPrice8.setBounds(153, 259, 147, 25);

        jLabel44.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 0, 255));
        jLabel44.setText("Monthly Coach Report");
        jPanel12.add(jLabel44);
        jLabel44.setBounds(120, 20, 220, 22);

        coachReport6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport6.setForeground(new java.awt.Color(0, 51, 255));
        coachReport6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport6.setRowHeight(30);
        jScrollPane9.setViewportView(coachReport6);

        jPanel12.add(jScrollPane9);
        jScrollPane9.setBounds(30, 90, 340, 190);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(null);

        selectName9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName9.setForeground(new java.awt.Color(0, 102, 255));
        jPanel13.add(selectName9);
        selectName9.setBounds(153, 78, 147, 20);

        selectStatus9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus9.setForeground(new java.awt.Color(0, 102, 255));
        jPanel13.add(selectStatus9);
        selectStatus9.setBounds(153, 228, 147, 25);

        selectPrice9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice9.setForeground(new java.awt.Color(0, 102, 255));
        jPanel13.add(selectPrice9);
        selectPrice9.setBounds(153, 259, 147, 25);

        jLabel45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 0, 255));
        jLabel45.setText("Monthly Coach Report");
        jPanel13.add(jLabel45);
        jLabel45.setBounds(120, 20, 220, 22);

        coachReport7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport7.setForeground(new java.awt.Color(0, 51, 255));
        coachReport7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport7.setRowHeight(30);
        jScrollPane10.setViewportView(coachReport7);

        jPanel13.add(jScrollPane10);
        jScrollPane10.setBounds(30, 90, 340, 190);

        jPanel12.add(jPanel13);
        jPanel13.setBounds(550, 290, 440, 310);

        jPanel10.add(jPanel12);
        jPanel12.setBounds(550, 290, 440, 310);

        jPanel4.add(jPanel10);
        jPanel10.setBounds(550, 290, 440, 310);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(1050, 190, 440, 570);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        selectName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName1.setForeground(new java.awt.Color(0, 102, 255));
        jPanel5.add(selectName1);
        selectName1.setBounds(153, 78, 147, 20);

        jLabel37.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 0, 255));
        jLabel37.setText("Monthly Learner Report");
        jPanel5.add(jLabel37);
        jLabel37.setBounds(90, 40, 230, 22);

        userReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userReport.setForeground(new java.awt.Color(0, 51, 255));
        userReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Learner Name", "Total Booked", "Total Cancelled", "Total Attended"
            }
        ));
        userReport.setRowHeight(30);
        jScrollPane2.setViewportView(userReport);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(30, 90, 380, 470);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(80, 180, 430, 580);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(null);

        selectName10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName10.setForeground(new java.awt.Color(0, 102, 255));
        jPanel14.add(selectName10);
        selectName10.setBounds(153, 78, 147, 20);

        jLabel46.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 0, 255));
        jLabel46.setText("Monthly Coach Report");
        jPanel14.add(jLabel46);
        jLabel46.setBounds(110, 40, 220, 22);

        coachReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport.setForeground(new java.awt.Color(0, 51, 255));
        coachReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport.setRowHeight(30);
        jScrollPane11.setViewportView(coachReport);

        jPanel14.add(jScrollPane11);
        jScrollPane11.setBounds(30, 90, 340, 460);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(null);

        selectName11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName11.setForeground(new java.awt.Color(0, 102, 255));
        jPanel15.add(selectName11);
        selectName11.setBounds(153, 78, 147, 20);

        selectStatus11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus11.setForeground(new java.awt.Color(0, 102, 255));
        jPanel15.add(selectStatus11);
        selectStatus11.setBounds(153, 228, 147, 25);

        selectPrice11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice11.setForeground(new java.awt.Color(0, 102, 255));
        jPanel15.add(selectPrice11);
        selectPrice11.setBounds(153, 259, 147, 25);

        jLabel47.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 0, 255));
        jLabel47.setText("Monthly Coach Report");
        jPanel15.add(jLabel47);
        jLabel47.setBounds(120, 20, 220, 22);

        coachReport9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport9.setForeground(new java.awt.Color(0, 51, 255));
        coachReport9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport9.setRowHeight(30);
        jScrollPane12.setViewportView(coachReport9);

        jPanel15.add(jScrollPane12);
        jScrollPane12.setBounds(30, 90, 340, 190);

        jPanel14.add(jPanel15);
        jPanel15.setBounds(550, 290, 440, 310);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(null);

        selectName12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName12.setForeground(new java.awt.Color(0, 102, 255));
        jPanel16.add(selectName12);
        selectName12.setBounds(153, 78, 147, 20);

        selectStatus12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus12.setForeground(new java.awt.Color(0, 102, 255));
        jPanel16.add(selectStatus12);
        selectStatus12.setBounds(153, 228, 147, 25);

        selectPrice12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice12.setForeground(new java.awt.Color(0, 102, 255));
        jPanel16.add(selectPrice12);
        selectPrice12.setBounds(153, 259, 147, 25);

        jLabel48.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 0, 255));
        jLabel48.setText("Monthly Coach Report");
        jPanel16.add(jLabel48);
        jLabel48.setBounds(120, 20, 220, 22);

        coachReport10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport10.setForeground(new java.awt.Color(0, 51, 255));
        coachReport10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport10.setRowHeight(30);
        jScrollPane13.setViewportView(coachReport10);

        jPanel16.add(jScrollPane13);
        jScrollPane13.setBounds(30, 90, 340, 190);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(null);

        selectName13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName13.setForeground(new java.awt.Color(0, 102, 255));
        jPanel17.add(selectName13);
        selectName13.setBounds(153, 78, 147, 20);

        selectStatus13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus13.setForeground(new java.awt.Color(0, 102, 255));
        jPanel17.add(selectStatus13);
        selectStatus13.setBounds(153, 228, 147, 25);

        selectPrice13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice13.setForeground(new java.awt.Color(0, 102, 255));
        jPanel17.add(selectPrice13);
        selectPrice13.setBounds(153, 259, 147, 25);

        jLabel49.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 0, 255));
        jLabel49.setText("Monthly Coach Report");
        jPanel17.add(jLabel49);
        jLabel49.setBounds(120, 20, 220, 22);

        coachReport11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport11.setForeground(new java.awt.Color(0, 51, 255));
        coachReport11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport11.setRowHeight(30);
        jScrollPane14.setViewportView(coachReport11);

        jPanel17.add(jScrollPane14);
        jScrollPane14.setBounds(30, 90, 340, 190);

        jPanel16.add(jPanel17);
        jPanel17.setBounds(550, 290, 440, 310);

        jPanel14.add(jPanel16);
        jPanel16.setBounds(550, 290, 440, 310);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(null);

        selectName14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName14.setForeground(new java.awt.Color(0, 102, 255));
        jPanel18.add(selectName14);
        selectName14.setBounds(153, 78, 147, 20);

        selectStatus14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus14.setForeground(new java.awt.Color(0, 102, 255));
        jPanel18.add(selectStatus14);
        selectStatus14.setBounds(153, 228, 147, 25);

        selectPrice14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice14.setForeground(new java.awt.Color(0, 102, 255));
        jPanel18.add(selectPrice14);
        selectPrice14.setBounds(153, 259, 147, 25);

        jLabel50.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 0, 255));
        jLabel50.setText("Monthly Coach Report");
        jPanel18.add(jLabel50);
        jLabel50.setBounds(120, 20, 220, 22);

        coachReport12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport12.setForeground(new java.awt.Color(0, 51, 255));
        coachReport12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport12.setRowHeight(30);
        jScrollPane15.setViewportView(coachReport12);

        jPanel18.add(jScrollPane15);
        jScrollPane15.setBounds(30, 90, 340, 190);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(null);

        selectName15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName15.setForeground(new java.awt.Color(0, 102, 255));
        jPanel19.add(selectName15);
        selectName15.setBounds(153, 78, 147, 20);

        selectStatus15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus15.setForeground(new java.awt.Color(0, 102, 255));
        jPanel19.add(selectStatus15);
        selectStatus15.setBounds(153, 228, 147, 25);

        selectPrice15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice15.setForeground(new java.awt.Color(0, 102, 255));
        jPanel19.add(selectPrice15);
        selectPrice15.setBounds(153, 259, 147, 25);

        jLabel51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 0, 255));
        jLabel51.setText("Monthly Coach Report");
        jPanel19.add(jLabel51);
        jLabel51.setBounds(120, 20, 220, 22);

        coachReport13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport13.setForeground(new java.awt.Color(0, 51, 255));
        coachReport13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport13.setRowHeight(30);
        jScrollPane16.setViewportView(coachReport13);

        jPanel19.add(jScrollPane16);
        jScrollPane16.setBounds(30, 90, 340, 190);

        jPanel18.add(jPanel19);
        jPanel19.setBounds(550, 290, 440, 310);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(null);

        selectName16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName16.setForeground(new java.awt.Color(0, 102, 255));
        jPanel20.add(selectName16);
        selectName16.setBounds(153, 78, 147, 20);

        selectStatus16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus16.setForeground(new java.awt.Color(0, 102, 255));
        jPanel20.add(selectStatus16);
        selectStatus16.setBounds(153, 228, 147, 25);

        selectPrice16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice16.setForeground(new java.awt.Color(0, 102, 255));
        jPanel20.add(selectPrice16);
        selectPrice16.setBounds(153, 259, 147, 25);

        jLabel52.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 0, 255));
        jLabel52.setText("Monthly Coach Report");
        jPanel20.add(jLabel52);
        jLabel52.setBounds(120, 20, 220, 22);

        coachReport14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport14.setForeground(new java.awt.Color(0, 51, 255));
        coachReport14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport14.setRowHeight(30);
        jScrollPane17.setViewportView(coachReport14);

        jPanel20.add(jScrollPane17);
        jScrollPane17.setBounds(30, 90, 340, 190);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(null);

        selectName17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectName17.setForeground(new java.awt.Color(0, 102, 255));
        jPanel21.add(selectName17);
        selectName17.setBounds(153, 78, 147, 20);

        selectStatus17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStatus17.setForeground(new java.awt.Color(0, 102, 255));
        jPanel21.add(selectStatus17);
        selectStatus17.setBounds(153, 228, 147, 25);

        selectPrice17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPrice17.setForeground(new java.awt.Color(0, 102, 255));
        jPanel21.add(selectPrice17);
        selectPrice17.setBounds(153, 259, 147, 25);

        jLabel53.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 0, 255));
        jLabel53.setText("Monthly Coach Report");
        jPanel21.add(jLabel53);
        jLabel53.setBounds(120, 20, 220, 22);

        coachReport15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachReport15.setForeground(new java.awt.Color(0, 51, 255));
        coachReport15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Average Ratings"
            }
        ));
        coachReport15.setRowHeight(30);
        jScrollPane18.setViewportView(coachReport15);

        jPanel21.add(jScrollPane18);
        jScrollPane18.setBounds(30, 90, 340, 190);

        jPanel20.add(jPanel21);
        jPanel21.setBounds(550, 290, 440, 310);

        jPanel18.add(jPanel20);
        jPanel20.setBounds(550, 290, 440, 310);

        jPanel14.add(jPanel18);
        jPanel18.setBounds(550, 290, 440, 310);

        getContentPane().add(jPanel14);
        jPanel14.setBounds(560, 180, 440, 580);

        backgroundImage.setText("jLabel1");
        backgroundImage.setPreferredSize(new java.awt.Dimension(1530, 829));
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 1530, 829);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeButtonActionPerformed
        // TODO add your handling code here:
        if(userId==0)
        {
            this.setVisible(false);
            new AdminDashboard().setVisible(true);
        }else
        {
            this.setVisible(false);
            new UserDashboard(userId).setVisible(true);
        }
        
    }//GEN-LAST:event_backHomeButtonActionPerformed

    
    //get ratinga monthly report from rating and booking table
    public void getMonthlyLearnerReport() {
        DefaultTableModel tbmodel = (DefaultTableModel) userReport.getModel();
        int user_id;
        String totalBooking;
        String totalCancel;
        String totalAttend;
        //get all user details
        List<User> user_details = new UserController().fetchAllUser();
        for (int i = 0; i < user_details.size(); i++) {
            //validation for learner only
            if (user_details.get(i).getRole().equalsIgnoreCase("Learner")) {
                //call booking_details method by user id
                List<Map<String, String>> booking_details = new BookingController().getBookingDetailsByUserId(i + 1);
                for (int j = 0; j < booking_details.size(); j++) {
                    user_id = Integer.parseInt(booking_details.get(j).get("userId"));
                    user_name = new UserController().getUserById(user_id).username;
                    totalBooking = booking_details.get(j).get("totalBooking");
                    totalCancel = booking_details.get(j).get("totalCancel");
                    totalAttend = booking_details.get(j).get("totalAttend");
                    String[] rowData = {user_name, totalBooking, totalCancel, totalAttend};
                    tbmodel.addRow(rowData);
                }
            }
        }
    }

    //get total avg rating by coach
    public void getMonthlyCoachReport() {
        DefaultTableModel tbmodel = (DefaultTableModel) coachReport.getModel();
        int coachId;
        String avgRating;
        String coachName;
        //fetch coach details
        List<User> coach_details = new UserController().fetchAllCoach();
        RatingController ratig = new RatingController();
        for (int j = 0; j < coach_details.size(); j++) {
            coachId = coach_details.get(j).getUserId();
            //get coach ratings details by coach id
            List<Map<String, String>> ratings = ratig.getAverageRatingByCoach(j + 1);
            for (int i = 0; i < ratings.size(); i++) {
                coachName = new UserController().getUserById(coachId).username;
                avgRating = ratings.get(i).get("avgRating");
                //display coach details on jtable
                String[] rowData = {coachName, avgRating};
                tbmodel.addRow(rowData);
            }
        }
    }
    
    public void fetchLessonRating() {
        DefaultTableModel tbmodel = (DefaultTableModel) ratingReport.getModel();
        int userId;
        String userName;
        int lessonId;
        String lessonName;
        String rating;
        List<Map<String, String>> rating_details = new RatingController().loadRatingData();
        for (int i = 0; i < rating_details.size(); i++) {
            userId = Integer.parseInt(rating_details.get(i).get("userId"));
            lessonId = Integer.parseInt(rating_details.get(i).get("lessonId"));
            userName = new UserController().getUserById(userId).username;
            lessonName = new LessonController().getLessonById(lessonId).lessonName;
            rating = rating_details.get(i).get("rating");
            //display coach details on jtable
            String[] rowData = {userName,lessonName,rating};
            tbmodel.addRow(rowData);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlyReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backHomeButton;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JTable coachReport;
    private javax.swing.JTable coachReport1;
    private javax.swing.JTable coachReport10;
    private javax.swing.JTable coachReport11;
    private javax.swing.JTable coachReport12;
    private javax.swing.JTable coachReport13;
    private javax.swing.JTable coachReport14;
    private javax.swing.JTable coachReport15;
    private javax.swing.JTable coachReport2;
    private javax.swing.JTable coachReport3;
    private javax.swing.JTable coachReport4;
    private javax.swing.JTable coachReport5;
    private javax.swing.JTable coachReport6;
    private javax.swing.JTable coachReport7;
    private javax.swing.JTable coachReport9;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable ratingReport;
    private javax.swing.JLabel selectName;
    private javax.swing.JLabel selectName1;
    private javax.swing.JLabel selectName10;
    private javax.swing.JLabel selectName11;
    private javax.swing.JLabel selectName12;
    private javax.swing.JLabel selectName13;
    private javax.swing.JLabel selectName14;
    private javax.swing.JLabel selectName15;
    private javax.swing.JLabel selectName16;
    private javax.swing.JLabel selectName17;
    private javax.swing.JLabel selectName2;
    private javax.swing.JLabel selectName4;
    private javax.swing.JLabel selectName5;
    private javax.swing.JLabel selectName6;
    private javax.swing.JLabel selectName7;
    private javax.swing.JLabel selectName8;
    private javax.swing.JLabel selectName9;
    private javax.swing.JLabel selectPrice;
    private javax.swing.JLabel selectPrice11;
    private javax.swing.JLabel selectPrice12;
    private javax.swing.JLabel selectPrice13;
    private javax.swing.JLabel selectPrice14;
    private javax.swing.JLabel selectPrice15;
    private javax.swing.JLabel selectPrice16;
    private javax.swing.JLabel selectPrice17;
    private javax.swing.JLabel selectPrice2;
    private javax.swing.JLabel selectPrice4;
    private javax.swing.JLabel selectPrice5;
    private javax.swing.JLabel selectPrice6;
    private javax.swing.JLabel selectPrice7;
    private javax.swing.JLabel selectPrice8;
    private javax.swing.JLabel selectPrice9;
    private javax.swing.JLabel selectStatus;
    private javax.swing.JLabel selectStatus11;
    private javax.swing.JLabel selectStatus12;
    private javax.swing.JLabel selectStatus13;
    private javax.swing.JLabel selectStatus14;
    private javax.swing.JLabel selectStatus15;
    private javax.swing.JLabel selectStatus16;
    private javax.swing.JLabel selectStatus17;
    private javax.swing.JLabel selectStatus2;
    private javax.swing.JLabel selectStatus4;
    private javax.swing.JLabel selectStatus5;
    private javax.swing.JLabel selectStatus6;
    private javax.swing.JLabel selectStatus7;
    private javax.swing.JLabel selectStatus8;
    private javax.swing.JLabel selectStatus9;
    private javax.swing.JTable userReport;
    // End of variables declaration//GEN-END:variables
}
